### PR TITLE
Id 10 pjc cycle 2

### PR DESCRIPTION
**Pull request by codalogic**
I might have got a bit carried away with this!  Hopefully you're not too shocked at the changes.

There are a few places where I wasn't sure which of a few options should be documented, so I picked the one I thought most likely and documented that.  So, as with the rest of the text, if you disagree with something, let me know.

I've proceeded on the basis that AOR will work fine!  I wanted to see what the text might look like, and also figured getting text related to it in there might give us the opportunity for a few rounds of word-smithing.  If AOR doesn't work out it should be easy enough to revert the text.

I need to switch to another task for a while.  Leaving this for a while will allow me to look at it with fresher eyes.

If you want to publish it as an I-D so that we have something active, that's fine by me, but we can also wait until we've had a chance to go over it again.

### CODE REVIEW

**Comment by anewton1998** [comment]
Some of this is hard to read in the xml and txt diffs, so I need to accept the PR and go from there. However, from what I can tell it all looks good... really good. Thanks.

**Comment by codalogic** [comment]
I stopped committing the .txt and .html versions because the page numbers in the .txt and the fact that paragraphs were all on one line for the .html seemed to make them less than helpful.

Did you mean to close the PR, or merge it?

If you want to look at it before merging, the final .txt version is at:
    https://raw.githubusercontent.com/codalogic/jcr/id-10-pjc-cycle-2/draft-newton-json-content-rules-10-pjc.txt

and I've put the .html at:
   http://json-content-rules.org/draft-newton-json-content-rules-10-pjc.html

**Comment by anewton1998** [comment]
That was a WOOOPS! I was seriously under caffeinated at that hour.

-andy

**Comment by codalogic** [comment]
:-)

**Comment by codalogic** [comment]
FYI - I've updated test_figs.sh, but not run it.  Hopefully there won't be any surprises.

**Pull request merged**
